export const constants = {
    locateTextGridData: {
        noRowsLabel: "Không có dữ liệu",
        noResultsOverlayLabel: "Không tìm thấy dữ liệu tương ứng",
        errorOverlayDefaultLabel: "An error occurred.",
        toolbarDensity: "Hiển thị",
        toolbarDensityLabel: "Hiển thị",
        toolbarDensityCompact: "Nhỏ gọn",
        toolbarDensityStandard: "Bình thường",
        toolbarDensityComfortable: "Rộng rãi",
        toolbarColumns: "Cột",
        toolbarColumnsLabel: "Chọn cột",
        toolbarFilters: 'Bộ lọc' as any,
        toolbarFiltersLabel: "Hiện bộ lọc",
        toolbarFiltersTooltipHide: "Ẩn bộ lọc",
        toolbarFiltersTooltipShow: "Hiện bộ lọc",
        toolbarFiltersTooltipActive: e => 1 !== e ? `${e} active filters` : `${e} active filter`,
        toolbarExport: "Xuất ra",
        toolbarExportLabel: "Xuất ra",
        toolbarExportCSV: "Tải xuống file CSV",
        toolbarExportPrint: "Bản in",
        columnsPanelTextFieldLabel: "Tìm cột",
        columnsPanelTextFieldPlaceholder: "Tiêu đề cột",
        columnsPanelDragIconLabel: "Sắp xếp",
        columnsPanelShowAllButton: "Hiện tất cả",
        columnsPanelHideAllButton: "Ẩn tất cả",
        filterPanelAddFilter: "Thêm bộ lọc",
        filterPanelDeleteIconLabel: "Xóa",
        filterPanelOperators: "Toán tử",
        filterPanelOperatorAnd: "Và",
        filterPanelOperatorOr: "Hoặc",
        filterPanelColumns: "Các cột",
        filterPanelInputLabel: "Giá trị",
        filterPanelInputPlaceholder: "Giá trị lọc",
        filterOperatorContains: "chứa",
        filterOperatorEquals: "bằng",
        filterOperatorStartsWith: "bắt đầu với",
        filterOperatorEndsWith: "kết thúc với",
        filterOperatorIs: "là",
        filterOperatorNot: "không là",
        filterOperatorAfter: "is after",
        filterOperatorOnOrAfter: "is on or after",
        filterOperatorBefore: "is before",
        filterOperatorOnOrBefore: "is on or before",
        filterOperatorIsEmpty: "is empty",
        filterOperatorIsNotEmpty: "is not empty",
        filterValueAny: "any",
        filterValueTrue: "true",
        filterValueFalse: "false",
        columnMenuLabel: "Menu",
        columnMenuShowColumns: "Hiện cột",
        columnMenuFilter: "Lọc",
        columnMenuHideColumn: "Ẩn",
        columnMenuUnsort: "Không sắp xếp",
        columnMenuSortAsc: "Tăng dần",
        columnMenuSortDesc: "Giảm dần",
        columnHeaderFiltersTooltipActive: e => 1 !== e ? `${e} active filters` : `${e} active filter`,
        columnHeaderFiltersLabel: "Hiện bộ lọc",
        columnHeaderSortIconLabel: "Sắp xếp",
        footerRowSelected: e => 1 !== e ? `${e.toLocaleString()} được chọn` : `${e.toLocaleString()} được chọn`,
        footerTotalRows: "Tổng số bản ghi:",
        footerTotalVisibleRows: (e, t) => `${e.toLocaleString()} of ${t.toLocaleString()}`,
        checkboxSelectionHeaderName: "Chọn",
        booleanCellTrueLabel: "đúng",
        booleanCellFalseLabel: "sai",
        actionsCellMore: "hơn nữa",
        pinToLeft: "Pin to left",
        pinToRight: "Pin to right",
        unpin: "Unpin",
        treeDataGroupingHeaderName: "Group",
        treeDataExpand: "see children",
        treeDataCollapse: "hide children",
        MuiTablePagination: {}
    }
}